### ISSUE TITLE
May need an update to go along with 0.6.7 of the parent?

### ISSUE THREAD

**Issue by tommyettinger** [crykn/libgdx-screenmanager-gwt#1]
I'm not sure how much needs changing, if anything, but when dependencies specify the 0.6.7 version of libgdx-screenmanager, they probably don't expect to need 0.6.6 of libgdx-screenmanager-gwt.

**Comment by crykn** [comment]
Sorry for the late reply! Apparently I had the notifications for this repo turned off... The recently released version 0.6.8 does once again offer both libgdx-screenmanager and libgdx-screenmanager-gwt dependencies.
